export const fundementals = [
  {
    name: "At attention",
    fname: "AtAttention",
    huVar: "",
    tempoVar: "",
    description:
      "Act of going to attention from at ease.\n***Note: Do not move at attention",
    vocals: "Rest, 1, 2!",
  },
  {
    name: "At ease",
    fname: "AtEase",
    huVar: "",
    tempoVar: "",
    description:
      "Act of going from at attention to at ease\n***Note: Can only go to at ease with horns down, Only fundamental that can be perfomed  at ease is called to attention",
    vocals: "Rest, 1!",
  },
  {
    name: "Left Face",
    fname: "LFace",
    huVar: "LFaceHU",
    tempoVar: "",
    description:
      "Turn to the left. Spin on the heel of the left foot and push with the ball of the right foot\n***Note: Movements must be in rhythm with the call",
    vocals: "1, 2!",
  },
  {
    name: "Right Face",
    fname: "RFace",
    huVar: "RFaceHU",
    tempoVar: "",
    description:
      "Turn to the right. Spin on the heel of the right foot and push with the ball of the left foot\n***Note: Movements must be in rhythm with the call",
    vocals: "1, 2!",
  },
  {
    name: "About Face",
    fname: "AFace",
    huVar: "AFaceHU",
    tempoVar: "",
    description:
      "Turn around. Move right foot slightly behind and to the left of the left foot. Spin on the ball of the right foot and heel of the left foot",
    vocals: "1, 2!",
  },
  {
    name: "Mark time drill",
    fname: "MTDrill",
    huVar: "MTDrillHU",
    tempoVar: "",
    description:
      "Learning how to marktime one movement at a time. Rest on the vocal rest then extend the left foot as if wearing high heels.\nThen move to a chairstep position and comback down",
    vocals: "Rest, 1, 2, 3, 4, 5, 6, 7, 8!",
  },
  {
    name: "Mark time",
    fname: "MarkTime",
    huVar: "MarkTimeHU",
    tempoVar: "",
    description: "Chairstepping in place",
    vocals: "Up, 1, 2, 3, 4, 5, 6, 7, 8!",
  },
  {
    name: "Foward March 8-5",
    fname: "FowardMarch8",
    huVar: "FowardMarch8UP",
    tempoVar: "FowardMarch8180",
    description: "Forward Movement at an 8-5 step",
    vocals:
      'Up 1, [2, 3, 4] (either ""Keeping Going if there are more  or ""Thats It"" if that is the end) Up halt kick!',
  },
  {
    name: "Foward March 16-5",
    fname: "FowardMarch16",
    huVar: "FowardMarch16UP",
    tempoVar: "FowardMarch16180",
    description: "Forward Movement at an 16-5 step",
    vocals:
      'Up 1, [2, 3, 4] (either ""Keeping Going if there are more or ""Thats It"" if that is the end) Up halt kick!',
  },
  {
    name: "Step foward about face",
    fname: "SFAF",
    huVar: "SFAFHU",
    tempoVar: "",
    description: "Turn around with chairstep",
    vocals: "Rest 1, 2, 3!",
  },
  {
    name: "Box of rights",
    fname: "BoR",
    huVar: "BoRHU",
    tempoVar: "BoR180",
    description:
      "Foward March followed by a right flank four time in a row without flanking the last time\n***Note: The end position will be the same but the orientation will be off by 90 degrees",
    vocals: "Foward March Vocals",
  },
  {
    name: "Box of lefts",
    fname: "BoL",
    huVar: "BoLHU",
    tempoVar: "BoL180",
    description:
      "Foward March followed by a left flank four time in a row without flanking the last time\n***Note: The end position will be the same but the orientation will be off by 90 degrees",
    vocals: "Foward March Vocals",
  },
  {
    name: "Regular TTR",
    fname: "RTTR",
    huVar: "RTTRHU",
    tempoVar: "",
    description: "Turn 180 degrees while forward marching",
    vocals: "Regular!",
  },
  {
    name: "Box TTR",
    fname: "BTTR",
    huVar: "BTTRHU",
    tempoVar: "",
    description: "Turn 180 degrees taking 4 counts instead of 1",
    vocals: "Box, T, T, R!",
  },
  {
    name: "Backwards March",
    fname: "BackwardMarch",
    huVar: "BackwardMarchHU",
    tempoVar: "BackwardMarchHU180",
    description: "Backwards movement at an 8-5 step",
    vocals: "Forward March Vocals",
  },
  {
    name: "Slide TTR",
    fname: "STTR",
    huVar: "STTRHU",
    tempoVar: "STTRHU180",
    description: "Regular TTR in the middle of an 8",
    vocals: "1, 2, 3, 4!",
  },
  {
    name: "Right Lateral Slide",
    fname: "RLS",
    huVar: "RLSHU",
    tempoVar: "",
    description:
      "Sideways movement right\n***Note: Keep the upperbody and lower body perpendicular to each other (keep upperbody facing forward)",
    vocals: "Forward March Vocals",
  },
  {
    name: "Left lateral slide",
    fname: "LLS",
    huVar: "LLSHU",
    tempoVar: "",
    description: "Sideways movement left",
    vocals: "Forward March Vocals",
  },
  {
    name: "Left Backwards lateral slide",
    fname: "LBLS",
    huVar: "LBLSHU",
    tempoVar: "",
    description: "Sideways movement left with lower body switched",
    vocals: "Forward March Vocals",
  },
  {
    name: "Right Backwards lateral slide",
    fname: "RBLS",
    huVar: "RBLSHU",
    tempoVar: "",
    description: "Sideways movement right with lower body switched",
    vocals: "Forward March Vocals",
  },
  {
    name: "Right Horn Slide",
    fname: "RHS",
    huVar: "RHSHU",
    tempoVar: "",
    description:
      "Lateral with an upper body flank in the beggining and end of the movement",
    vocals: "Forward March Vocals",
  },
  {
    name: "Left horn slide",
    fname: "LHS",
    huVar: "LHSHU",
    tempoVar: "",
    description:
      "Lateral with an upper body flank in the beggining and end of the movement",
    vocals: "Forward March Vocals",
  },
  {
    name: "Foward March 6-5 step",
    fname: "FowardMarch6",
    huVar: "ForwardMarch6HU",
    tempoVar: "",
    description: "Forward movement with stride step",
    vocals: "1, 2, 3, 4, 5, 6!",
  },
  {
    name: "Backwards March 16-5 step",
    fname: "BackwardMarch16",
    huVar: "BackwardMarchHU",
    tempoVar: "",
    description: "Backwards movement at an 16-5 step",
    vocals: "1, 2, 3, 4, 5, 6, 7, 8!, 9, 10, 11, 12, 13, 14, 15, 16",
  },
  {
    name: "Slow Turn 8 counts",
    fname: "SlowTurn8",
    huVar: "SlowTurn8HU",
    tempoVar: "",
    description: "Slowly turn in place in 8 counts",
    vocals: "1, 2, 3, 4!, 5, 6, 7, 8",
  },
  {
    name: "Slow Turn 4 counts",
    fname: "SlowTurn4",
    huVar: "SlowTurn4HU",
    tempoVar: "",
    description: "Slowly turn in place in 4 counts",
    vocals: "1, 2!, 3, 4",
  },
  {
    name: "Oblique 8-5",
    fname: "Oblq8",
    huVar: "Oblq8HU",
    tempoVar: "",
    description:
      "March at a 45 degree angle with an flank at the beggining and end\n***Note: The step size is still 8-5, but will take 12 steps to go 5 yards because of trig! Arm swing on 1, 5, 9",
    vocals: "1, 2, 3, 4, 5, 6!, 7, 8, 9, 10, 11, 12",
  },
  {
    name: "Oblique 6-5",
    fname: "Oblq6",
    huVar: "Oblq6HU",
    tempoVar: "",
    description:
      "March at a 45 degree angle with an flashless flank at the beggining and a flashing flank at the end\n***Note: The step size is still 6-5, but will take 8 steps to go 5 yards because of trig!",
    vocals: "1, 2, 3, 4!, 5, 6, 7, 8",
  },
  {
    name: "Side Step",
    fname: "SideStep",
    huVar: "SideStepHU",
    tempoVar: "",
    description: "Move to the LEFT while facing forward",
    vocals: "Side, step; side, step!",
  },
  {
    name: "Step Side",
    fname: "StepSide",
    huVar: "StepSideHU",
    tempoVar: "",
    description: "Move to the RIGHT while facing forward",
    vocals: "Step, side; step, side!",
  },
  {
    name: "Up step turn to the rear",
    fname: "UPStepTTR",
    huVar: "UPStepTTRHU",
    tempoVar: "",
    description: "Turn 180 and continue moving afterward",
    vocals: "Up, step, turn!",
  },
  {
    name: "Bow Tie Drill",
    fname: "BowTie",
    huVar: "BowTieHU",
    tempoVar: "",
    description:
      "An oblique followed by a backwards march, followed by an obliquqe going the other direction, into another backwards march",
    vocals: "",
  },
  {
    name: "Ramp Cadence",
    fname: "RampCadence",
    huVar: "",
    tempoVar: "",
    description: "Mark time during the ramp entrance",
    vocals: "Mimick the drums",
  },
  {
    name: "Ramp Coversion",
    fname: "RampConversion",
    huVar: "",
    tempoVar: "",
    description:
      "Conversion going from the candences to the intro of buckeye battle cry",
    vocals: "fight, 1, 2, 3, 4, 5, 6, 7, 8",
  },
  {
    name: "Sloopy Step",
    fname: "Sloopy",
    huVar: "",
    tempoVar: "",
    description: "Movement during a sloopy performance",
    vocals: "",
  },
  {
    name: "Hats Off",
    fname: "HatsOff",
    huVar: "HatsOff123",
    tempoVar: "",
    description: "Bow to the audience after a performance",
    vocals: "Off 2, 3, 4; Down, 2, 3, 4; Up, 2, 3, 4; On, 2; Down, 2; O, HI, O",
  },
  {
    name: "Step Kicks",
    fname: "StepKicks",
    huVar: "StepKicksHU",
    tempoVar: "",
    description: "Special forwards marching",
    vocals: "Up; step, kick x8",
  },
  {
    name: "Two Seventy",
    fname: "270",
    huVar: "",
    tempoVar: "",
    description: "WE DONT DO THIS ANYMORE",
    vocals: "",
  },
];
